# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 19:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amtrakmain', '0002_auto_20170419_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTrip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.IntegerField(default=0, verbose_name='Fare')),
                ('trip_date', models.DateField(default=datetime.date.today, verbose_name='Trip Date')),
                ('trip_end', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='t_end+', to='amtrakmain.Station', verbose_name='Trip End Station')),
                ('trip_pay_method', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amtrakmain.PaymentMethod', verbose_name='Choose Payment')),
                ('trip_segment_end', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='s_end+', to='amtrakmain.Segment', verbose_name='Segment End')),
                ('trip_segment_start', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='s_start+', to='amtrakmain.Segment', verbose_name='Segment Start')),
                ('trip_start', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='t_start+', to='amtrakmain.Station', verbose_name='Trip Start Station')),
            ],
        ),
        migrations.RemoveField(
            model_name='tickettrips',
            name='trip_end',
        ),
        migrations.RemoveField(
            model_name='tickettrips',
            name='trip_payment_method',
        ),
        migrations.RemoveField(
            model_name='tickettrips',
            name='trip_segment_end',
        ),
        migrations.RemoveField(
            model_name='tickettrips',
            name='trip_segment_start',
        ),
        migrations.RemoveField(
            model_name='tickettrips',
            name='trip_start',
        ),
        migrations.RemoveField(
            model_name='tickettrips',
            name='trip_train',
        ),
        migrations.AddField(
            model_name='train',
            name='train_number',
            field=models.IntegerField(default=0, verbose_name='Train Number'),
        ),
        migrations.DeleteModel(
            name='TicketTrips',
        ),
        migrations.AddField(
            model_name='tickettrip',
            name='trip_train',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='amtrakmain.Train', verbose_name='Train'),
        ),
    ]
