# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amtrakmain', '0004_auto_20170420_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='train_days',
            field=models.CharField(help_text='M-T-W-Th-F-S-Su', max_length=20, verbose_name='Days train runs'),
        ),
    ]
