# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amtrakmain', '0006_auto_20170420_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatsFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sf_date', models.DateField(verbose_name='Date')),
                ('sf_count', models.IntegerField(default=0, verbose_name='Free Seats in Segment')),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='seg_distance',
            field=models.IntegerField(default=0, verbose_name='Mileage Between Stations'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='seg_fare',
            field=models.IntegerField(verbose_name='Fare'),
        ),
        migrations.AlterField(
            model_name='tickettrip',
            name='trip_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_end+', to='amtrakmain.Station', verbose_name='Trip End Station'),
        ),
        migrations.AlterField(
            model_name='tickettrip',
            name='trip_segment_end',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_end+', to='amtrakmain.Segment', verbose_name='Segment End'),
        ),
        migrations.AlterField(
            model_name='tickettrip',
            name='trip_segment_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_start+', to='amtrakmain.Segment', verbose_name='Segment Start'),
        ),
        migrations.AlterField(
            model_name='tickettrip',
            name='trip_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='t_start+', to='amtrakmain.Station', verbose_name='Trip Start Station'),
        ),
        migrations.AlterField(
            model_name='tickettrip',
            name='trip_train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amtrakmain.Train', verbose_name='Train'),
        ),
        migrations.AddField(
            model_name='seatsfree',
            name='sf_segment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seg+', to='amtrakmain.Segment', verbose_name='Segment'),
        ),
        migrations.AddField(
            model_name='seatsfree',
            name='sf_train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sf_train+', to='amtrakmain.Train', verbose_name='Train in Segment'),
        ),
        migrations.AlterUniqueTogether(
            name='seatsfree',
            unique_together=set([('sf_segment', 'sf_train')]),
        ),
    ]
