# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amtrakmain', '0008_auto_20170421_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stopsat',
            name='sa_time_out',
            field=models.TimeField(null=True, verbose_name='Time-out of train at Station'),
        ),
    ]
