# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amtrakmain', '0013_auto_20170422_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettrip',
            old_name='trip_end',
            new_name='trip_end_station',
        ),
        migrations.RenameField(
            model_name='tickettrip',
            old_name='trip_start',
            new_name='trip_start_station',
        ),
    ]
