# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amtrakmain', '0015_auto_20170426_0145'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seatsfree',
            unique_together=set([]),
        ),
    ]
