# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amtrakmain', '0005_auto_20170420_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='end_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_end', to='amtrakmain.Station', verbose_name='End Station'),
        ),
        migrations.AlterField(
            model_name='train',
            name='start_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_start', to='amtrakmain.Station', verbose_name='Start Station'),
        ),
    ]
