# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amtrakmain', '0007_auto_20170420_2100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stopsat',
            name='sa_station',
        ),
        migrations.AddField(
            model_name='stopsat',
            name='sa_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station+', to='amtrakmain.Station', verbose_name='Station Where Train Stops'),
        ),
        migrations.AlterField(
            model_name='stopsat',
            name='sa_time_in',
            field=models.TimeField(verbose_name='Time-In of Train at Station'),
        ),
        migrations.AlterField(
            model_name='stopsat',
            name='sa_time_out',
            field=models.TimeField(verbose_name='Time-out of train at Station'),
        ),
        migrations.AlterField(
            model_name='stopsat',
            name='sa_train',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train+', to='amtrakmain.Train', verbose_name='Which Train?'),
        ),
    ]
