# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amtrakmain', '0009_auto_20170421_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettrip',
            name='trip_direction',
            field=models.BooleanField(default=1, help_text='North = 1, South = 0', verbose_name='Direction'),
        ),
        migrations.AlterField(
            model_name='stopsat',
            name='sa_time_out',
            field=models.TimeField(blank=True, null=True, verbose_name='Time-out of train at Station'),
        ),
        migrations.AlterField(
            model_name='tickettrip',
            name='trip_segment_end',
            field=models.ForeignKey(help_text='Shows only north-end station of segment', on_delete=django.db.models.deletion.CASCADE, related_name='s_end+', to='amtrakmain.Segment', verbose_name='Segment End'),
        ),
        migrations.AlterField(
            model_name='tickettrip',
            name='trip_segment_start',
            field=models.ForeignKey(help_text='Shows only north-end station of segment', on_delete=django.db.models.deletion.CASCADE, related_name='s_start+', to='amtrakmain.Segment', verbose_name='Segment Start'),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_direction',
            field=models.BooleanField(help_text='North = 1, South = 0', verbose_name='Direction'),
        ),
    ]
