# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 04:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amtrakmain', '0010_auto_20170422_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettrip',
            name='trip_direction',
            field=models.NullBooleanField(help_text='North = 1, South = 0', verbose_name='Direction'),
        ),
    ]
