# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 17:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amtrakmain', '0011_auto_20170422_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettrip',
            name='trip_direction',
        ),
        migrations.AlterField(
            model_name='seatsfree',
            name='sf_count',
            field=models.PositiveIntegerField(help_text='0 <= n <= 448', validators=[django.core.validators.MaxValueValidator(448)], verbose_name='Free Seats in Segment'),
        ),
        migrations.AlterField(
            model_name='seatsfree',
            name='sf_date',
            field=models.DateTimeField(help_text='All reservations start June 1st 2017, 6:00am', verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='seatsfree',
            name='sf_segment',
            field=models.ForeignKey(help_text='Shows only north-end station of segment', on_delete=django.db.models.deletion.CASCADE, related_name='seg+', to='amtrakmain.Segment', verbose_name='Segment'),
        ),
    ]
