# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amtrakmain', '0012_auto_20170422_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettrip',
            old_name='fare',
            new_name='trip_fare',
        ),
    ]
