# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amtrakmain', '0014_auto_20170422_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettrip',
            name='trip_date',
            field=models.DateField(verbose_name='Trip Date'),
        ),
    ]
